import {
  LayoutDashboard,
  Settings, // Mapped to Sliders for Master Config in App.tsx
  MonitorPlay,
  Database,
  Droplet,
  Binary,
  MessageSquare,
  Network,
  Gavel,
  ShieldCheck,
  Zap,
  History,
  Rocket,
  Blocks,
  Box,
  Eye,
  Sliders,
} from 'lucide-react';
import { AppModule } from './types';

export const APP_MODULES: AppModule[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    desc: 'Overview',
    color: 'text-white',
  },
  {
    id: 'master_config',
    label: 'Master Config',
    icon: Sliders,
    desc: 'Hardware, AI & Risk',
    color: 'text-white',
  },
  {
    id: 'monitor',
    label: 'Live Monitor',
    icon: MonitorPlay,
    desc: 'Real-time HUD',
    color: 'text-neon-blue',
  },
  {
    id: 'datamining',
    label: 'Data Mining',
    icon: Database,
    desc: 'Ingestion Pipeline',
    color: 'text-blue-400',
  },
  {
    id: 'liquidity',
    label: 'Liquidity Engine',
    icon: Droplet,
    desc: 'Whale Watching',
    color: 'text-cyan-400',
  },
  {
    id: 'feature_engineering',
    label: 'Feature Engineering',
    icon: Binary,
    desc: 'Signal Extraction',
    color: 'text-indigo-400',
  },
  {
    id: 'sentiment',
    label: 'NLP & Sentiment',
    icon: MessageSquare,
    desc: 'Social Analysis',
    color: 'text-pink-400',
  },
  {
    id: 'neural_net',
    label: 'Neural Network',
    icon: Network,
    desc: 'Deep Learning',
    color: 'text-violet-400',
  },
  {
    id: 'decision_engine',
    label: 'Decision Engine',
    icon: Gavel,
    desc: 'Trade Logic',
    color: 'text-orange-400',
  },
  {
    id: 'risk_engine',
    label: 'Risk Engine',
    icon: ShieldCheck,
    desc: 'Safety Protocols',
    color: 'text-red-400',
  },
  {
    id: 'execution_engine',
    label: 'Execution Engine',
    icon: Zap,
    desc: 'Order Routing',
    color: 'text-yellow-400',
  },
  {
    id: 'backtesting',
    label: 'Backtesting',
    icon: History,
    desc: 'Simulation Lab',
    color: 'text-indigo-300',
  },
  {
    id: 'deployment',
    label: 'Deployment',
    icon: Rocket,
    desc: 'Ops Center',
    color: 'text-green-500',
  },
  {
    id: 'advanced_ops',
    label: 'Advanced Modules',
    icon: Blocks,
    desc: 'Web3 & Auto-Scale',
    color: 'text-cyan-300',
  },
  {
    id: 'rust_core',
    label: 'Rust HFT Core',
    icon: Box,
    desc: 'HFT Latency',
    color: 'text-orange-500',
  },
  {
    id: 'hidden_steps',
    label: 'Hidden Steps',
    icon: Eye,
    desc: 'OpSec & Legal',
    color: 'text-gray-400',
  },
];
